#Alert format
ALERT <alert name>
  IF <expression>
  [ FOR <duration>]
  [ LABELS <label set> ]
  [ ANNOTATIONS <label set> ]


 
#Alert example

groups:
- name: example
  rules:
  - alert: cpuUsge
    expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{job='node_exporter',mode="idle"}[5m])) * 100 ) > 95
    for: 1m
    labels: 
    # Alerting severity
      severity: critical
    annotations:
      summary: Machine under heavy load
      

# Alert example 2

groups:
- name: Important Instance
  rules:
  # Alerts for any instance that is unreachable for > 5m 
  - alert: InstanceDown 
    expr: up==0
    for: 5m
    labels: 
      severity: page
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance}} of job {{ $labels.job}} has been down for more than 5 minutes." 
  
